name: "Add annotations from Jest JUnit report"
description: "Add annotations from Jest JUnit report"

inputs:
  github_token:
    description: "GITHUB_TOKEN"
    required: true

  check_name:
    description: "The name of the check. For example, code-coverage"
    required: true

  report_path:
    description: "File path of a generated HTML report, used for reading failing test cases"
    required: true

  report_filename:
    description: "Filename of a generated HTML report"
    # if `report_filename` is not specified it will merge all reports found in `report_path`

runs:
  using: "node12"
  main: "dist/index.js"
